release:
  name_template: "{{ .Version }} - {{ .Date }}"
  draft: true

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }}

nfpms:
  - 
    homepage: https://github.com/BrightLocal/{{ .ProjectName }}
    description: HTTP-server to execute shell commands. Designed for development, prototyping or remote control.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: shell2http.1
        dst: /usr/share/man/man1/shell2http.1
      - src: LICENSE
        dst: /usr/share/doc/shell2http/copyright
      - src: README.md
        dst: /usr/share/doc/shell2http/README.md

archives:
  -
    files:
      - README*
      - LICENSE*
      - "*.1"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge branch'
      - '^go fmt'
