language: go
sudo: required
services:
  - docker

env:
  global:
    - APP_NAME=shell2http
    - CURRENT_GO_VERSION="1.9"
    - DOCKER_USERNAME=msoap
    - secure: "vO3gq16EiNtNXeNrZM6T2r4ysqWtxv9S1AphV1DMQKfpo3f827qMBYZ+HyeWD7jFFvb9lJxmzf2KXh/zSWSRoAkFtmcM8ENbG+AdQb1JNNIyrkb3hvUzU1Qkia8SqEc0fBysTtiyCKNDK6Cp1+xOSZ+6icVGUh4BtiEv2DLTCcN8U3IgSxu5Dm4iR0nlTeTLWV5wORFaOHNbuh/aQVtyjMmm8hsZDpcobLZU3x4XvyrIwqbbkvNLR/ctr49nIyGYySqeJ1pJRNeELpWsItHExagn9Xa8B2+LTHd59+dyrifmJaYCsv+d/j5qxHqgl4ibBY8/cgNI/+3cb7/41o9sTLVCwAJFU9zWG/FkSykJ2EXd0vnDNs0cbZ8S+xxjpcQZx1L3op1c6YSt6/0b3yi7CnIACJXLDqddXutR3is54QKQ56VE6eOYiOeS2ALsJaWJR9Obi/4wHiH7w+ySFmz+BRNACWBkfdHy3P9nIVh9VqEd33bDpWeAZK+0ROprePPOAdJi60c5uflcjT2e0Vz5FlXJdOX71nPyPdsivMAGUaKC3Nxuodxs6QvMh1XtbcTozU+6ZwU+I8Q/66g9/fVPaF/sJl4aZuZQEvXCpi3GRhRhcZHsihOXal+QIXlsI+13bkKYcJl7lKBIa3yI7Yh8sx3Zp34rtv54WRzV9kOkWqo="

go:
  - 1.8.x
  - 1.9.x
  - master

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/philwinder/gocoverage
  - go get github.com/kisielk/errcheck
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker version

install: go get -t ./...

script:
  - go test -race -v ./...
  - go vet ./...
  - errcheck ./...
  - diff <(gofmt -d .) <(echo -n "")
  - if [[ $TRAVIS_GO_VERSION =~ $CURRENT_GO_VERSION ]]; then
      gocoverage && goveralls -coverprofile=profile.cov -service=travis-ci || true;
    fi

after_success:
  - if [[ $TRAVIS_GO_VERSION =~ $CURRENT_GO_VERSION ]] && [[ $TRAVIS_BRANCH == "master" || -n $TRAVIS_TAG ]] && [[ $TRAVIS_EVENT_TYPE == "push" ]]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
      docker login -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD" quay.io &&
      docker build -t $DOCKER_USERNAME/$APP_NAME:latest . &&
      docker tag $DOCKER_USERNAME/$APP_NAME:latest quay.io/$DOCKER_USERNAME/$APP_NAME:latest &&
      docker push $DOCKER_USERNAME/$APP_NAME:latest &&
      docker push quay.io/$DOCKER_USERNAME/$APP_NAME:latest;
      if [[ -n $TRAVIS_TAG ]]; then
        docker tag $DOCKER_USERNAME/$APP_NAME:latest $DOCKER_USERNAME/$APP_NAME:$TRAVIS_TAG &&
        docker tag $DOCKER_USERNAME/$APP_NAME:latest quay.io/$DOCKER_USERNAME/$APP_NAME:$TRAVIS_TAG &&
        docker push $DOCKER_USERNAME/$APP_NAME:$TRAVIS_TAG &&
        docker push quay.io/$DOCKER_USERNAME/$APP_NAME:$TRAVIS_TAG;
      fi;
      rm -f $APP_NAME;
    fi

before_deploy:
  - curl -SL https://raw.githubusercontent.com/msoap/etc/master/golang-cross-build/golang-cross-build.sh > $GOPATH/bin/golang-cross-build.sh
  - chmod 700 $GOPATH/bin/golang-cross-build.sh
  - gem install --no-ri --no-rdoc fpm
  - golang-cross-build.sh $APP_NAME
  - ls -l *.zip *.tar.gz *.deb

deploy:
  provider: releases
  api_key:
    secure: dXAy5WWWVozf+prMJNjQT6s4JqAXZEyOZ+LeaBzz8k7WZzCvHaLg+qdIpXbIL0G/hc7hW9WEhj/apcjiodwPhqKjy52dw3bUclHqUxxR5ZvgyZyb7qyyLoPqDtygHgGMX+UANgkMTUIM3auP/W6jvmV5mc7ddTZah+z+l542J6AdDOs+m97dlqNLdlz5AdCr5uY0O2sIsmpD4WFxINsdcG67Lj6V9HK8fzlCz0aGeKvcapgF1r4iXxWxvwSGMJwdljYKGyX2wm5Sp2Q7IklX/zNPAPJZtthUvbaaDUMkmYjb6YcAPmFZ1IhtFkpurNzNGfKCSz7784ZEf1b+dDYLNAKwv6hG1YKLadFoplecaH0xLcYwBZvwq9pDaJpX20I5sbNQDyEOCjrBaxB1RyCr/m9m8tOXZzfn6YIUHAbimhL4g98smQ797fQn4/zquSeKkqF2mMA5v5hLdXI2snwK/e2zDxTCwpw4NNyxjY6PgXO61vL4EE8Xq6nl+rKDZ7B+BXWHmP5kxuxHHVpYZPKUnQUmpbUkD62RM5hZbJ6+h07WF3wVvgFc+l8aNK8W+uWff5OZBbyV7mWdfpHtxVR0xSG/6eGIiCVJ6cFLyjV2JRQHk9x+aZKSEErfkuYawyt+tIl7OtsqBNBtYHE4ARgvwb7uPbX4EgTpcQmOsRCNBsQ=
  file_glob: "true"
  file:
    - "*.zip"
    - "*.tar.gz"
    - "*.deb"
  skip_cleanup: true
  on:
    tags: true
    branch: master
    condition: $TRAVIS_GO_VERSION =~ $CURRENT_GO_VERSION
    repo: msoap/$APP_NAME
