name: shell2http
version: '1.13'
summary: Executing shell commands via HTTP server
description: |
  HTTP-server for executing shell commands. Designed for develop, prototype or remote control.
  Settings through two command line arguments, path and shell command.
  By default bind to :8080.
  https://github.com/msoap/shell2http
grade: stable
confinement: strict
base: core18

parts:
  shell2http:
    plugin: go
    go-channel: latest/stable
    go-importpath: github.com/msoap/shell2http
    source: .
    source-type: git
    build-packages:
      - gcc

apps:
  shell2http:
    command: shell2http
    plugs: [network-bind, network, home]
