name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.20.x']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Install errcheck
      run: go install github.com/kisielk/errcheck@latest

    - name: errcheck
      run: errcheck -verbose ./...

    - name: gofmt check
      run: diff <(gofmt -d .) <(echo -n "")

    - name: Test
      run: go test -race -v ./...
